# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: songs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsongs.proto\"^\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.SongCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.SongRecommendation\".\n\x12SongRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t*H\n\x0cSongCategory\x12\x07\n\x03POP\x10\x00\x12\x0b\n\x07HIP_HOP\x10\x01\x12\x0e\n\nELECTRONIC\x10\x02\x12\x08\n\x04\x46OLK\x10\x04\x12\x08\n\x04ROCK\x10\x05\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'songs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONGCATEGORY']._serialized_start=231
  _globals['_SONGCATEGORY']._serialized_end=303
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=15
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=109
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=111
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=181
  _globals['_SONGRECOMMENDATION']._serialized_start=183
  _globals['_SONGRECOMMENDATION']._serialized_end=229
  _globals['_RECOMMENDATIONS']._serialized_start=305
  _globals['_RECOMMENDATIONS']._serialized_end=384
# @@protoc_insertion_point(module_scope)
